-d C:\KY_8\EGG_FRESH\egg_fresh_v4\impl\gwsynthesis\egg_fresh_v2.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\KY_8\EGG_FRESH\egg_fresh_v4\src\tang_nano_20k.cst
-cfg C:\KY_8\EGG_FRESH\egg_fresh_v4\impl\pnr\device.cfg
-sdc C:\KY_8\EGG_FRESH\egg_fresh_v4\src\timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
